# Generated by Django 3.0.2 on 2020-01-16 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='raiting',
            new_name='rating',
        ),
    ]
