# Generated by Django 3.0.3 on 2020-02-22 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_auto_20200116_0527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='arraival_date',
            new_name='arrival_date',
        ),
    ]
